// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj2sf4WKL72_9oPhSmZtdbsNUqTpQ0LqQ',
    appId: '1:412387496472:web:99097c95da830662fe296d',
    messagingSenderId: '412387496472',
    projectId: 'saldochecker',
    authDomain: 'saldochecker.firebaseapp.com',
    storageBucket: 'saldochecker.appspot.com',
    measurementId: 'G-Q30HM32RKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1LXRuKU9AN_FuOqJWvupVaqLqnV2uXM0',
    appId: '1:412387496472:android:cdbcd9b9b3d4fe2afe296d',
    messagingSenderId: '412387496472',
    projectId: 'saldochecker',
    storageBucket: 'saldochecker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA79CZsY5NOP754JQjz07ZPgTt1Oj4o2Jo',
    appId: '1:412387496472:ios:2ff56511c69f3e8dfe296d',
    messagingSenderId: '412387496472',
    projectId: 'saldochecker',
    storageBucket: 'saldochecker.appspot.com',
    iosClientId: '412387496472-le3h6uk8fa6bmef7v1662qaj5joi7h4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.saldochecker',
  );
}
